In [3]:
import numpy as np


In [21]:
import pandas as pd

In [23]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
newarr = arr.reshape(5, 2)

print(newarr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [7]:
arr = np.arange(1, 21)


In [10]:
extracted_elements = arr[5:15]

In [13]:
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15]


In [29]:
data = {'apples': 3, 'bananas': 2, 'oranges': 1}


In [31]:
series = pd.Series(data)

In [33]:
series['pears'] = 4


In [35]:

print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [37]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 27, 36, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}

In [40]:
df = pd.DataFrame(data)

In [42]:
print(df)

      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   35    Male
3    David   40    Male
4      Eva   22  Female
5    Frank   28    Male
6    Grace   33  Female
7   Hannah   27  Female
8      Ian   36    Male
9     Jack   31    Male


In [44]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 
                     'Programmer', 'Manager', 'Analyst', 'Programmer']


In [47]:
print(df)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   35    Male     Analyst
3    David   40    Male  Programmer
4      Eva   22  Female     Manager
5    Frank   28    Male     Analyst
6    Grace   33  Female  Programmer
7   Hannah   27  Female     Manager
8      Ian   36    Male     Analyst
9     Jack   31    Male  Programmer


In [49]:
filtered_df = df[df['age'] >= 30]

In [51]:
print(filtered_df)

      name  age  gender  occupation
1      Bob   30    Male     Manager
2  Charlie   35    Male     Analyst
3    David   40    Male  Programmer
6    Grace   33  Female  Programmer
8      Ian   36    Male     Analyst
9     Jack   31    Male  Programmer


In [53]:
csv_file = 'filtered_data.csv'
filtered_df.to_csv(csv_file, index=False)


In [55]:
read_df = pd.read_csv(csv_file)

In [57]:
print(read_df.head())

      name  age  gender  occupation
0      Bob   30    Male     Manager
1  Charlie   35    Male     Analyst
2    David   40    Male  Programmer
3    Grace   33  Female  Programmer
4      Ian   36    Male     Analyst
